hombre(pedro).
hombre(daniel).
hombre(juan).
hombre(miguel).
hombre(roberto).
hombre(diego).
mujer(juana).
mujer(maria).
mujer(ana).
mujer(luisa).
mujer(diana).
mujer(carmen).
mujer(lisa).
padre(pedro,juan).
padre(pedro,luisa).
padre(juana,juan).
padre(juana,luisa).
padre(luisa, diego).
padre(ana,miguel).
padre(ana,diana).
padre(ana,roberto).
padre(juan,miguel).
padre(juan,diana).
padre(juan,roberto).
padre(maria,carmen).
padre(maria,lisa).
padre(diego,carmen).
padre(diego,lisa).
hijo(X,Y):-padre(Y,X).
